# Path to Qt5.
# Both WITH_QT5 and CMAKE_PREFIX_PATH can be changed in CMake.vars.
# This is just to handle the case WITH_QT5 is and CMAKE_PREFIX_PATH is not.
IF(WIN32)
    IF(NOT(CMAKE_PREFIX_PATH))
      SET(CMAKE_PREFIX_PATH "C:\\Qt\\Qt5.0.2\\5.0.2\\msvc2010_opengl\\")
    ENDIF()
ENDIF()

# Add QT.

# Link OpenGL and Zlib when needed.
IF(WIN32)
    FIND_PACKAGE(OpenGL REQUIRED)
    FIND_PACKAGE(ZLIB REQUIRED)
	INCLUDE_DIRECTORIES(${ZLIB_INCLUDE_DIRS})
ENDIF()

SET(CMAKE_AUTOMOC TRUE)

FIND_PACKAGE(Qt5Core REQUIRED)
FIND_PACKAGE(Qt5Gui REQUIRED)
FIND_PACKAGE(Qt5OpenGL REQUIRED)
FIND_PACKAGE(Qt5PrintSupport REQUIRED)
FIND_PACKAGE(Qt5Svg REQUIRED)
FIND_PACKAGE(Qt5Network REQUIRED)
FIND_PACKAGE(Qt5Widgets REQUIRED)
FIND_PACKAGE(Qt5WebKit REQUIRED)
FIND_PACKAGE(Qt5WebKitWidgets REQUIRED)
FIND_PACKAGE(Qt5Xml REQUIRED)
FIND_PACKAGE(Qt5XmlPatterns REQUIRED)
FIND_PACKAGE(Qt5UiTools REQUIRED)

IF(DEFINED QT_USE_FILE)
  INCLUDE(${QT_USE_FILE})
ENDIF()
ADD_DEFINITIONS(${QT_DEFINITIONS})
