PROJECT(agros_plugin_{{ID}})
INCLUDE_DIRECTORIES(${CMAKE_AGROS_DIRECTORY}/agros-library)
INCLUDE_DIRECTORIES(${CMAKE_AGROS_DIRECTORY}/3rdparty)
INCLUDE_DIRECTORIES(.)

IF(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated -Wno-deprecated-declarations -Wno-missing-declarations -Wno-return-type")
ENDIF()

# This overrides CXX flags for MSVC
# IF(MSVC)
#  SET(CMAKE_CXX_FLAGS_RELEASE        "${CMAKE_CXX_FLAGS_RELEASE} /Ob2")
# ENDIF(MSVC)

SET(SOURCES {{ID}}_filter.cpp {{ID}}_weakform.cpp {{ID}}_volumeintegral.cpp {{ID}}_surfaceintegral.cpp {{ID}}_localvalue.cpp {{ID}}_force.cpp {{ID}}_interface.cpp)
SET(HEADERS {{ID}}_filter.h {{ID}}_weakform.h {{ID}}_volumeintegral.h {{ID}}_surfaceintegral.h {{ID}}_localvalue.h {{ID}}_force.h {{ID}}_interface.h)

ADD_DEFINITIONS(-DQT_PLUGIN)
ADD_DEFINITIONS(-DQT_SHARED)
ADD_DEFINITIONS(-DQT_DLL)
ADD_LIBRARY(${PROJECT_NAME} SHARED ${SOURCES} ${HEADERS})

# ${DEAL_II_LIBRARIES}
SET(LIBRARIES_TO_LINK ${OPENGL_LIBRARIES} ${PYTHON_MODLIBS} ${PYTHON_LIB} ${PLUGINS_AGROS_LIBRARY} ${PTHREAD_LIBRARY} ${MUMPS_LIBRARIES} ${CMAKE_AGROS_DIRECTORY}/dealii/build/lib/libdeal_II.so ${UMFPACK_LIBRARY} ${AMD_LIBRARY} ${SuiteSparse_config_LIBRARY} ${BLAS_LIBRARIES})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIBRARIES_TO_LINK} Qt6::Core Qt6::Network)

#IF(AGROS_PLUGINS_DEBUG AND WIN32)
#TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${TBB_LIBRARY_DEBUG})
#ELSE()
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${TBB_LIBRARY})
#ENDIF()

SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CMAKE_AGROS_DIRECTORY}/libs)
INSTALL(TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
