PROJECT(agros_plugin_{{ID}})
INCLUDE_DIRECTORIES(${CMAKE_AGROS_SOURCE}/agros-library)
INCLUDE_DIRECTORIES(${CMAKE_AGROS_SOURCE}/3rdparty)
INCLUDE_DIRECTORIES(.)

IF(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated -Wno-deprecated-declarations -Wno-missing-declarations -Wno-return-type")
ENDIF()

# This overrides CXX flags for MSVC
IF(MSVC)
	IF(${CMAKE_BUILD_TYPE} STREQUAL "Release")
	  SET(DEAL_LIBRARY ${CMAKE_AGROS_SOURCE}/dealii/build/lib/deal_II.lib)
	ELSE()
           SET(DEAL_LIBRARY ${CMAKE_AGROS_SOURCE}/dealii/build/lib/deal_II.g.lib)
	ENDIF()
	SET(DXFLIB_LIBRARY ${CMAKE_SOURCE_DIR}/../usr/lib/agros_3rdparty_dxflib.lib)
	SET(NLOPTLIB_LIBRARY ${CMAKE_SOURCE_DIR}/../usr/lib/agros_3rdparty_nlopt2.lib)
	SET(MATIO_LIBRARY ${CMAKE_SOURCE_DIR}/../usr/lib/agros_3rdparty_matio.lib)
	SET(BAYESOPTLIB_LIBRARY ${CMAKE_SOURCE_DIR}/../usr/lib/agros_3rdparty_bayesopt.lib)
	SET(TRIANGLE_LIBRARY ${CMAKE_SOURCE_DIR}/../usr/lib/agros_3rdparty_triangle.lib)
	SET(QUAZIP_LIBRARY ${CMAKE_SOURCE_DIR}/../usr/lib/agros_3rdparty_quazip.lib)
ENDIF(MSVC)

SET(SOURCES {{ID}}_filter.cpp {{ID}}_weakform.cpp {{ID}}_volumeintegral.cpp {{ID}}_surfaceintegral.cpp {{ID}}_localvalue.cpp {{ID}}_force.cpp {{ID}}_interface.cpp)
SET(HEADERS {{ID}}_filter.h {{ID}}_weakform.h {{ID}}_volumeintegral.h {{ID}}_surfaceintegral.h {{ID}}_localvalue.h {{ID}}_force.h {{ID}}_interface.h)

ADD_DEFINITIONS(-DQT_PLUGIN)
ADD_DEFINITIONS(-DQT_SHARED)
ADD_DEFINITIONS(-DQT_DLL)
ADD_LIBRARY(${PROJECT_NAME} SHARED ${SOURCES} ${HEADERS})

SET(LIBRARIES_TO_LINK ${DEAL_LIBRARY} ${NLOPTLIB_LIBRARY} ${AMD_LIBRARY} ${MATIO_LIBRARY}  ${ZLIB_LIBRARY} ${TRIANGLE_LIBRARY} ${DXFLIB_LIBRARY} ${QUAZIP_LIBRARY} ${BAYESOPTLIB_LIBRARY} ${NLOPTLIB_LIBRARY} ${OPENGL_LIBRARIES} ${PYTHON_MODLIBS} ${PYTHON_LIB} ${PLUGINS_AGROS_LIBRARY} ${MUMPS_LIBRARIES}  ${ZLIB_LIBRARY} ${CTEMPLATE_LIBRARY} ${XercesC_LIBRARIES})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${LIBRARIES_TO_LINK} Qt6::Core Qt6::Network Qt6::Core5Compat)

#IF(AGROS_PLUGINS_DEBUG AND WIN32)
#TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${TBB_LIBRARY_DEBUG})
#ELSE()
# TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${TBB_LIBRARY})
#ENDIF()

SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/../usr/lib)
INSTALL(TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
