FIND_LIBRARY(MUMPS_COMMON_LIBRARY
    NAMES
    mumps_common
    PATHS
    $ENV{PETSC_DIR}/lib
    $ENV{PETSC_DIR}/$ENV{PETSC_ARCH}/lib
    $ENV{MUMPS_DIR}/lib
)

FIND_LIBRARY(DMUMPS_LIBRARY
    NAMES
    dmumps
    PATHS
    $ENV{PETSC_DIR}/lib
    $ENV{PETSC_DIR}/$ENV{PETSC_ARCH}/lib
    $ENV{MUMPS_DIR}/lib
)

message(STATUS "Mumps: ${DMUMPS_LIBRARY} ${MUMPS_COMMON_LIBRARY}" )
if ( MUMPS_COMMON_LIBRARY AND DMUMPS_LIBRARY )
  SET(MUMPS_LIBRARIES ${DMUMPS_LIBRARY} ${MUMPS_COMMON_LIBRARY})
endif()



include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MUMPS "Could not find MUMPS " MUMPS_LIBRARIES)
MARK_AS_ADVANCED(MUMPS_LIBRARIES)
